### ISSUE TITLE
Calling Stored Procedures

### ISSUE THREAD

**Issue by ebirukov** [mailru/activerecord#6]
Declaration example
```
//ar:serverConf:box1
//ar:procedure:bar.foo
//ar:backend:octopus
type FieldsFoo struct {
  InParams1 string `ar:""`
  InParams2 string `ar:""`
  Output  string `ar:"serializer:Output"`
  //InOutParam any - it is possible to set InOut parameters for relational database https://pkg.go.dev/database/sql#Out
}

or
//ar:serverConf:box1
//ar:namespace:bar.foo
//ar:backend:octopus
type ProcFieldsFoo struct {
  InParams1 string `ar:""`
  InParams2 string `ar:""`
  Output  string `ar:"serializer:Output"`
  //InOutParam any - it is possible to set InOut parameters for relational database https://pkg.go.dev/database/sql#Out
}


type (
  ParamsProcFoo struct {
    Params bool `ar:"fields:InParams1,InParams2;"`
  }

  SerializersFoo struct {
    Output *repository.Data `ar:"unmarshaler:MapstructureUnmarshal;marshaler:MapstructureMarshal"`
  }
)
```

code generated by this declaration
```
func CallProcedure(ctx context.Context, params ParamsFoo) (*Foo, error) {
  ...
  c, _ := box(ctx, 0, activerecord.ReplicaInstanceType)
  output, _ := octopus.CallLua(ctx, c, "bar.foo", params.Params1, params.Params2)
  ...
  return result(params, output), nil
}
```

Usage:

```
dict, err := foo.CallProcedure(ctx, ParamsFoo{InParams1:"1",InParams1:"2"}) )
var out *repository.Data
out = dict.GetOutput()
```

**Comment by sklukin** [comment]
Output это же по факту пустой интерфейс?

Хотелось бы все таки строгой типизации. Что бы приходящие данные натягивались на стуктуру, а параметры лежали в отдельной структуре. По типу индексов, но параметры

**Comment by ebirukov** [comment]
> Output это же по факту пустой интерфейс?
> 
> Хотелось бы все таки строгой типизации. Что бы приходящие данные натягивались на структуру, а параметры лежали в отдельной структуре. По типу индексов, но параметры

По задумке выходные параметры могут иметь сериализаторы аналогично существующим полям структур Fields
SerializersFoo struct {
    Output *repository.Data `ar:"unmarshaler:MapstructureUnmarshal;marshaler:MapstructureMarshal"`
  }

**Comment by Nikolo** [comment]
//ar:serverConf:box1
//ar:namespace:bar.foo
//ar:backend:octopus
type ProcFieldsFoo struct {
  ID uint64 `ar:"input;output"`
  Name string `ar:"output"`
  Email string `ar:"input;output"`
}

type ProcFieldsFoo struct {
  ID uint64 `ar:"input:2;output"`
  Name string `ar:"output"`
  Email string `ar:"input:1;output"`
  Status bool `ar:"input:3"`
}

**Comment by ebirukov** [comment]
[generator](https://github.com/mailru/activerecord/pull/8) mvp
and example 
- [declaration](https://github.com/mailru/activerecord-cookbook/blob/proc-example/example/model/repository/declaration/foo.go) 
- [usage](https://github.com/mailru/activerecord-cookbook/blob/proc-example/example/app_test.go#L19)

**Comment by ebirukov** [comment]
для вышеприведенной модели описания есть неоднозначность, возвращаемые параметры луашной процедуров можно реализовать  двумя способами:
1)  с несколькими возвращаемыми значениями
  func foo() return "out1", "out2". В этом случае придет несколько туплов с одним значением
2) с одним возвращаемое значение в виде тупла построенного так
   func foo() return box.tuple.new({"out1", "out2"}) и тогда придет один тупл с несколькими значениями

Т.е. в общем случае октопус возвращает двумерную модель и возникает неоднозначность мепинга результата на поля описанной в активрекорд структуры, разделять на поля тупл с несколькими значениями или брать в качестве значения единичный элемент тупла

Чтобы поддержать оба варианта приходит в голову решение добавить тег типа raw:N, col:K в описание поля в декларации активрекод, чтобы описаывать какое значение K из тупла N мепить на поле в декларации. 
Но кажется такое не актуально для реляционных БД и добавит сложности в описание
Кажется что для нашего варианта с луашным банком вариант 1 не нужен, не знаю используется ли он еще где-то в проектах с тарантулом и потребуется ли вообще
 @Nikolo  что думаешь насколько вариант с несколькими возвращаемыми значениями в луашных процедурах актуален для activerecord?

**Comment by ebirukov** [comment]
support storage procedure call

[example declaration ](https://github.com/mailru/activerecord-cookbook/blob/main/example/model/repository/declaration/foo.go)
[generated api](https://github.com/mailru/activerecord-cookbook/blob/main/example/model/repository/generated/foo)
[example test](https://github.com/mailru/activerecord-cookbook//blob/main/example/app_test.go#L58)
